apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      role: msvc-auth
  template:
    metadata:
      labels:
        role: msvc-auth
    spec:
      containers:
        - name: msvc-auth
          image: ciap35/msvc-auth:v1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: LB_USER_URI
              valueFrom:
                configMapKeyRef:
                  key: lb_user_uri
                  name: msvc-user
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-auth
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  selector:
    role: msvc-auth