apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-user
data:
  port: "8001"
  db_host: "mysql8:3306"
  database: "msvc_user"
  course.url: "msvc-course:8002"
  lb_auth_issuer_uri: http://192.168.23.176:31066 #MSVC-AUTH url from minikube cluster
  lb_user_uri: http://192.168.23.176:30811 #MSVC-USER url from minikube cluster
  #lb_auth_issuer_uri: "http://192.168.23.176:31380" #MSVC-AUTH url from minikube cluster
  #lb_user_uri: "http://192.168.23.176:30870" #MSVC-USER url from minikube cluster
  application.yaml: |-
    config:
      activeEnv: sample
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      activeEnv: dev
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      activeEnv: prod
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-course
data:
  port: "8002"
  db_host: "postgres14:5432"
  database: "msvc_course"
  user.url: "msvc-user:8001"