version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3506:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msvc_user
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: msvc_course
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-user:
    container_name: msvc-user
    image: ciap35/msvc-user:latest
    ports:
      - "8001:8001"
    env_file: ./msvc-user/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

  msvc-course:
    container_name: msvc-course
    image: ciap35/msvc-course:latest
    ports:
      - "8002:8002"
    #environment:
    #  PORT: 8002
    #  DB_HOST: postgres14:5432
    #  DB_DATABASE : msvc_course
    #  DB_USERNAME: postgres
    #  DB_PASSWORD: postgres
    #  USER_URL: msvc-user:8001
    env_file: ./msvc-course/.env
    networks:
      - spring
    depends_on:
      - postgres14
      - msvc-user
    restart: always

volumes:
  data-mysql:
  data-postgres:

networks:
  spring: